apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP  # 👈 cluster fermé sur une IP (par d'ouverture de port vers l'hote)
  selector:
    app: web       # 👈 correspond au label du Deployment
  ports:
    - protocol: TCP
      port: 80          # 👈 port exposé dans le cluster (Service)
      targetPort: 80    # 👈 port du conteneur dans le Pod
