apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-api
  labels:
    app: sentiment-analysis-api
spec:
  type: NodePort
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  selector:
    app: sentiment-analysis-api