apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: eval
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30000
      protocol: TCP