apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-dags-folder
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi