apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: eval
spec:
  type: ClusterIP
  clusterIP: 10.43.0.42
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3307       # port exposé dans le cluster
      targetPort: 3306 # port du conteneur MySQL
      protocol: TCP