apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-data-folder-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: eval
    name: mysql-pvc-mysql-0
  hostPath:
    path: /data/mysql